### ISSUE TITLE
Refreshing page would expose all codes

### ISSUE THREAD

**Issue by hanseric245** [GoWP/Coupon-Codes-Display#1]
First: thanks for banging this code out. Found it on Reddit after Googing around for something that does this without charging $50/mo).

This is not so much a bug as it is probably a design consideration. 

I was all excited to use this and had it installed on my WP site. Tests great (even wrote a blog post about it! - http://itshans.com/displaying-single-use-coupon-codes-site/#comment-1712).

Then, about 10 mins later I realized there could be a flaw. The whole idea of single-use codes is that they keep someone from cleaning out one's inventory by distributing a multi-use coupon code to their friends, blogs, etc.

If a visitor refreshes the page delivering the code using Coupon-Codes-Display, they could effectively clean out all of one's single-use codes, which is effectively the same as giving them a multi-use code.

Is there some way to implement this so that this ability would be blocked?

**Comment by karpstrucking** [comment]
Hmm, good point. I suppose you could use a cookie for this - create a cookie when they receive a code, and then check for this cookie before displaying a new code. This approach still wouldn't stop someone savvy enough to delete the cookie in question, though. Another option would be to log the IP address when a code is given and check for the IP before giving the code. Again, not infallible but may be helpful.

**Comment by hanseric245** [comment]
Thanks for your reply.
Seems like IP logging would be best approach since I would suspect that more are familiar with how to circumvent cookie method than would be able to sidestep IP logging.
Is it particularly complicated to add IP logging to this?
Seems like the idea at the most rudimentary level would be to log said IP, then, if "IP already exists = yes" then show [Message].  
I'm not a dev though so wouldn't know how to add something like this myself.

**Comment by karpstrucking** [comment]
Yup, pretty much. I opened a branch with an example of this in bba3b8f4460227f7e87c4ad27e7b40a337dfe951

I imagine this would need some additional code to automatically expire IPs after a set amount of time and provide a way for one/more/all IPs to be flushed manually.

**Comment by hanseric245** [comment]
Nice. I would imagine that would be very workable.

**Comment by Elderrain** [comment]
I sent you a message on reddit and the same message on here 

I was wondering if you could help me figure out how to make your coupon code work with my site
I made the php file for my site http://www.amzdealsclub.us/wp-content/themes/Divi/test.html
However when i try the short code, http://www.amzdealsclub.us/test/ It is not showing the single use code with the short code

**Comment by karpstrucking** [comment]
@Elderrain it looks like you've not registered the shortcode with `add_shortcode` which is why it's not translating on the published page.

**Comment by Elderrain** [comment]
i tried using the add wordpress short code option,However it till not show any code at all.
